# Generated by Django 4.2.7 on 2023-12-14 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_alter_album_musician'),
        ('musician', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Musician',
        ),
    ]
